// <auto-generated />
using System;
using BillFolder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillFolder.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426193717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "card_statement_status", new[] { "open", "closed", "paid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "cycle_adjustment_type", new[] { "inflow", "outflow" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "expense_status", new[] { "pending", "paid", "overdue" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "income_origin_type", new[] { "work", "rent", "investment", "freelance", "gift", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "income_status", new[] { "expected", "received", "late", "not_occurred" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "savings_transaction_type", new[] { "deposit", "withdrawal", "yield", "transfer_out", "transfer_in" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("InstallmentsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("installments_count");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_card_entries_card");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_card_entries_template");

                    b.HasIndex("UserId", "PurchaseDate")
                        .HasDatabaseName("ix_card_entries_user_date");

                    b.ToTable("card_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_installments_count_min1", "installments_count >= 1");

                            t.HasCheckConstraint("ck_total_amount_nonneg", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntryRecurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_amount");

                    b.Property<Guid>("DefaultCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_category_id");

                    b.Property<string>("DefaultLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_label");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_entry_recurrences_user");

                    b.ToTable("card_entry_recurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_day_of_month", "day_of_month BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("LinkedExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_expense_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkedExpenseId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_statements_user");

                    b.HasIndex("CardId", "DueDate")
                        .HasDatabaseName("ix_card_statements_card_due");

                    b.ToTable("card_statements", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_pt");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CheckingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("Branch")
                        .HasColumnType("text")
                        .HasColumnName("branch");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("InitialBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("initial_balance");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_checking_one_primary_per_user")
                        .HasFilter("is_primary = true");

                    b.ToTable("checking_accounts", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CreditCardAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<short>("ClosingDay")
                        .HasColumnType("smallint")
                        .HasColumnName("closing_day");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<string>("IssuerBank")
                        .HasColumnType("text")
                        .HasColumnName("issuer_bank");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_credit_cards_user");

                    b.ToTable("credit_card_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_closing_day", "closing_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_due_day", "due_day BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsRecurrenceGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurrence_generated");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartDate")
                        .IsUnique();

                    b.HasIndex("UserId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_cycles_user_dates");

                    b.ToTable("cycles", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CycleAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("SourceSavingsTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_savings_transaction_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceSavingsTransactionId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_cycle_adjustments_user_date");

                    b.ToTable("cycle_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_amount_nonneg", "amount >= 0");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.DailyExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_daily_expenses_template");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_daily_expenses_user_date");

                    b.ToTable("daily_expenses", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.DailyExpenseRecurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<Guid>("DefaultAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_account_id");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_amount");

                    b.Property<Guid>("DefaultCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_category_id");

                    b.Property<string>("DefaultLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_label");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAccountId");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_daily_expense_recurrences_user");

                    b.ToTable("daily_expense_recurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_day_of_month", "day_of_month BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("expected_amount");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LinkedCardStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_card_statement_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<Guid?>("PaidFromAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_from_account_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LinkedCardStatementId");

                    b.HasIndex("PaidFromAccountId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_expenses_template");

                    b.HasIndex("UserId", "DueDate")
                        .HasDatabaseName("ix_expenses_user_due");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_expenses_status")
                        .HasFilter("status = 'overdue'");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.ExpenseRecurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_amount");

                    b.Property<Guid>("DefaultCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_category_id");

                    b.Property<string>("DefaultLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_label");

                    b.Property<short>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_expense_recurrences_user");

                    b.ToTable("expense_recurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_due_day", "due_day BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.IncomeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_amount");

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("expected_amount");

                    b.Property<DateOnly>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_income_entries_source");

                    b.HasIndex("UserId", "ExpectedDate")
                        .HasDatabaseName("ix_income_entries_user_date");

                    b.ToTable("income_entries", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_amount");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<short>("ExpectedDay")
                        .HasColumnType("smallint")
                        .HasColumnName("expected_day");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<int>("OriginType")
                        .HasColumnType("integer")
                        .HasColumnName("origin_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_income_sources_user");

                    b.ToTable("income_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_expected_day", "expected_day BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CardEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_entry_id");

                    b.Property<short>("InstallmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_number");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.HasKey("Id");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_installments_statement");

                    b.HasIndex("CardEntryId", "InstallmentNumber")
                        .IsUnique();

                    b.ToTable("installments", null, t =>
                        {
                            t.HasCheckConstraint("ck_installment_number_min1", "installment_number >= 1");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("Branch")
                        .HasColumnType("text")
                        .HasColumnName("branch");

                    b.Property<Guid>("CheckingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("checking_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("InitialBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("initial_balance");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckingAccountId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_savings_user");

                    b.ToTable("savings_accounts", (string)null);
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.SavingsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LinkedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_transaction_id");

                    b.Property<Guid>("SavingsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("savings_account_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTransactionId");

                    b.HasIndex("SavingsAccountId", "Date")
                        .HasDatabaseName("ix_savings_transactions_account_date");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_savings_transactions_user_date");

                    b.ToTable("savings_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_amount_nonneg", "amount >= 0");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CycleStartRule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("5th_business_day")
                        .HasColumnName("cycle_start_rule");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleOauthId")
                        .HasColumnType("text")
                        .HasColumnName("google_oauth_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleOauthId")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_auth_method_chk", "password_hash IS NOT NULL OR google_oauth_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntry", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CreditCardAccount", "Card")
                        .WithMany("CardEntries")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.CardEntryRecurrence", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CardEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Category");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntryRecurrence", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CreditCardAccount", "Card")
                        .WithMany("CardEntryRecurrences")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.Category", "DefaultCategory")
                        .WithMany()
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CardEntryRecurrences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("DefaultCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardStatement", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CreditCardAccount", "Card")
                        .WithMany("Statements")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.Expense", "LinkedExpense")
                        .WithMany()
                        .HasForeignKey("LinkedExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CardStatements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("LinkedExpense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CheckingAccount", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CheckingAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CreditCardAccount", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CreditCardAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Cycle", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("Cycles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CycleAdjustment", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.SavingsTransaction", "SourceSavingsTransaction")
                        .WithMany()
                        .HasForeignKey("SourceSavingsTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("CycleAdjustments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSavingsTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.DailyExpense", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CheckingAccount", "Account")
                        .WithMany("DailyExpenses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.DailyExpenseRecurrence", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("DailyExpenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.DailyExpenseRecurrence", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CheckingAccount", "DefaultAccount")
                        .WithMany("DailyExpenseRecurrences")
                        .HasForeignKey("DefaultAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.Category", "DefaultCategory")
                        .WithMany()
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("DailyExpenseRecurrences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultAccount");

                    b.Navigation("DefaultCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Expense", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.CardStatement", "LinkedCardStatement")
                        .WithMany("RelatedExpenses")
                        .HasForeignKey("LinkedCardStatementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.CheckingAccount", "PaidFromAccount")
                        .WithMany("ExpensesPaidFromHere")
                        .HasForeignKey("PaidFromAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.ExpenseRecurrence", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LinkedCardStatement");

                    b.Navigation("PaidFromAccount");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.ExpenseRecurrence", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.Category", "DefaultCategory")
                        .WithMany()
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("ExpenseRecurrences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.IncomeEntry", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.IncomeSource", "Source")
                        .WithMany("Entries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("IncomeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.IncomeSource", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("IncomeSources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.Installment", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CardEntry", "CardEntry")
                        .WithMany("Installments")
                        .HasForeignKey("CardEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.CardStatement", "Statement")
                        .WithMany("Installments")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardEntry");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.SavingsAccount", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.CheckingAccount", "CheckingAccount")
                        .WithOne("SavingsAccount")
                        .HasForeignKey("BillFolder.Domain.Entities.SavingsAccount", "CheckingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("SavingsAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckingAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.SavingsTransaction", b =>
                {
                    b.HasOne("BillFolder.Domain.Entities.SavingsTransaction", "LinkedTransaction")
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BillFolder.Domain.Entities.SavingsAccount", "SavingsAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillFolder.Domain.Entities.User", "User")
                        .WithMany("SavingsTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedTransaction");

                    b.Navigation("SavingsAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntry", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardEntryRecurrence", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CardStatement", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("RelatedExpenses");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CheckingAccount", b =>
                {
                    b.Navigation("DailyExpenseRecurrences");

                    b.Navigation("DailyExpenses");

                    b.Navigation("ExpensesPaidFromHere");

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.CreditCardAccount", b =>
                {
                    b.Navigation("CardEntries");

                    b.Navigation("CardEntryRecurrences");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.DailyExpenseRecurrence", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.ExpenseRecurrence", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.IncomeSource", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.SavingsAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BillFolder.Domain.Entities.User", b =>
                {
                    b.Navigation("CardEntries");

                    b.Navigation("CardEntryRecurrences");

                    b.Navigation("CardStatements");

                    b.Navigation("CheckingAccounts");

                    b.Navigation("CreditCardAccounts");

                    b.Navigation("CycleAdjustments");

                    b.Navigation("Cycles");

                    b.Navigation("DailyExpenseRecurrences");

                    b.Navigation("DailyExpenses");

                    b.Navigation("ExpenseRecurrences");

                    b.Navigation("Expenses");

                    b.Navigation("IncomeEntries");

                    b.Navigation("IncomeSources");

                    b.Navigation("SavingsAccounts");

                    b.Navigation("SavingsTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
